name: MLflow CI Training & Docker Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0
          pip install -r requirements.txt

      - name: Run MLflow Project (Training)
        run: |
          export MLFLOW_TRACKING_URI=$PWD/mlruns
          mlflow run MLProject --env-manager=local --experiment-name=Heart_Disease_Final_Model

      - name: Get Latest MLflow Run ID
        id: get_run
        run: |
          RUN_ID=$(find mlruns -type f -name "meta.yaml" -printf '%T@ %p\n' | sort -rn | head -1 | awk '{print $2}' | xargs dirname | xargs basename)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest RUN_ID: $RUN_ID"

      - name: Build Docker Image with MLflow
        run: |
          export MLFLOW_TRACKING_URI=$PWD/mlruns
          mlflow models build-docker \
            --model-uri runs:/$RUN_ID/model \
            --name heart-disease-model

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag heart-disease-model ${{ secrets.DOCKER_USERNAME }}/heart-disease-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/heart-disease-model:latest
